#!/bin/bash
set -e

ENV_NAME=$1
if [ -z "$ENV_NAME" ]; then
  echo "Usage: ./deploy-kong-gateway.sh <env>"
  exit 1
fi

source ../env/${ENV_NAME}.env
MANIFEST_DIR=../manifests/gateway

# --- Hardcoded cert/key (test values — rotate before real use) ---
CERT_DATA='-----BEGIN CERTIFICATE-----
MIICQTCCAeigAwIBAgIBATAKBggqhkjOPQQDBDBSMVAwCQYDVQQGEwJJTjBDBgNV
BAMePABrAG8AbgBuAGUAYwB0AC0AYQBtAGEAbgBfAGIAXwBvAHAAZQByAGEAdABv
AHIAXwBzAGUAYwBvAG4AZDAeFw0yNjA3MjAxNzQzMDZaFw0zNjA3MjAxNzQzMDZa
MFIxUDAJBgNVBAYTAklOMEMGA1UEAx48AGsAbwBuAG4AZQBjAHQALQBhAG0AYQBu
AF8AYgBfAG8AcABlAHIAYQB0AG8AcgBfAHMAZQBjAG8AbgBkMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEcVpqTGgtqZpEr5ciYX16hIceKVIhRWlvI3vlnLuOIAXr
xmtN084yFmcsGpGNe/eQL9bYY0SKSwp6G/1Ye7qhXqOBrjCBqzAMBgNVHRMBAf8E
AjAAMAsGA1UdDwQEAwIABjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
FwYJKwYBBAGCNxQCBAoMCGNlcnRUeXBlMCMGCSsGAQQBgjcVAgQWBBQBAQEBAQEB
AQEBAQEBAQEBAQEBATAcBgkrBgEEAYI3FQcEDzANBgUpAQEBAQIBCgIBFDATBgkr
BgEEAYI3FQEEBgIEABQACjAKBggqhkjOPQQDBANHADBEAiBQnNr0VMnY8789pPGS
8UDoBsPY0qH61687URvZBgDSmQIgbVOjIUICIiF92rr1kVJzzJH9Bnxl2kdtSk1r
3ruKWWM=
-----END CERTIFICATE-----'

KEY_DATA='-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxiy+djYOD3PNmqoW
ZbKImDkooH1rXgTluXzzAVD7gASgCgYIKoZIzj0DAQehRANCAARxWmpMaC2pmkSv
lyJhfXqEhx4pUiFFaW8je+Wcu44gBevGa03TzjIWZywakY1795Av1thjRIpLCnob
/Vh7uqFe
-----END PRIVATE KEY-----'

echo "Creating namespace $NAMESPACE..."
kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

echo "Creating cert secret $CLUSTER_CERT_SECRET_NAME..."
kubectl create secret generic $CLUSTER_CERT_SECRET_NAME \
  --from-literal=tls.crt="$CERT_DATA" \
  --from-literal=tls.key="$KEY_DATA" \
  -n $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

echo "Applying GatewayConfiguration..."
sed \
  -e "s|NAMESPACE_PLACEHOLDER|$NAMESPACE|g" \
  -e "s|GATEWAY_CONFIG_NAME_PLACEHOLDER|$GATEWAY_CONFIG_NAME|g" \
  -e "s|DATAPLANE_REPLICAS_PLACEHOLDER|$DATAPLANE_REPLICAS|g" \
  -e "s|IMAGE_PATH_PLACEHOLDER|$IMAGE_PATH|g" \
  -e "s|CLUSTER_CONTROL_PLANE_PLACEHOLDER|$CLUSTER_CONTROL_PLANE|g" \
  -e "s|CLUSTER_SERVER_NAME_PLACEHOLDER|$CLUSTER_SERVER_NAME|g" \
  -e "s|CLUSTER_TELEMETRY_ENDPOINT_PLACEHOLDER|$CLUSTER_TELEMETRY_ENDPOINT|g" \
  -e "s|CLUSTER_TELEMETRY_SERVER_NAME_PLACEHOLDER|$CLUSTER_TELEMETRY_SERVER_NAME|g" \
  -e "s|DATAPLANE_CPU_REQUEST_PLACEHOLDER|$DATAPLANE_CPU_REQUEST|g" \
  -e "s|DATAPLANE_MEMORY_REQUEST_PLACEHOLDER|$DATAPLANE_MEMORY_REQUEST|g" \
  -e "s|DATAPLANE_CPU_LIMIT_PLACEHOLDER|$DATAPLANE_CPU_LIMIT|g" \
  -e "s|DATAPLANE_MEMORY_LIMIT_PLACEHOLDER|$DATAPLANE_MEMORY_LIMIT|g" \
  -e "s|CERT_SECRET_NAME_PLACEHOLDER|$CLUSTER_CERT_SECRET_NAME|g" \
  -e "s|INGRESS_SERVICE_TYPE_PLACEHOLDER|$INGRESS_SERVICE_TYPE|g" \
  $MANIFEST_DIR/gateway-config.yaml | kubectl apply -f -

echo "Applying GatewayClass..."
sed \
  -e "s|NAMESPACE_PLACEHOLDER|$NAMESPACE|g" \
  -e "s|GATEWAY_CLASS_NAME_PLACEHOLDER|$GATEWAY_CLASS_NAME|g" \
  -e "s|GATEWAY_CONFIG_NAME_PLACEHOLDER|$GATEWAY_CONFIG_NAME|g" \
  $MANIFEST_DIR/gatewayclass.yaml | kubectl apply -f -

echo "Applying Gateway..."
sed \
  -e "s|NAMESPACE_PLACEHOLDER|$NAMESPACE|g" \
  -e "s|GATEWAY_NAME_PLACEHOLDER|$GATEWAY_NAME|g" \
  -e "s|GATEWAY_CLASS_NAME_PLACEHOLDER|$GATEWAY_CLASS_NAME|g" \
  $MANIFEST_DIR/gateway.yaml | kubectl apply -f -

sleep 30
kubectl get all -n $NAMESPACE
kubectl get gateway -n $NAMESPACE
kubectl get dataplane -n $NAMESPACE
