kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v2beta1
metadata:
  name: GATEWAY_CONFIG_NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
spec:
  dataPlaneOptions:
    deployment:
      replicas: DATAPLANE_REPLICAS_PLACEHOLDER
      podTemplateSpec:
        spec:
          containers:
            - name: proxy
              image: IMAGE_PATH_PLACEHOLDER
              env:
                - name: KONG_ROLE
                  value: "data_plane"
                - name: KONG_DATABASE
                  value: "off"
                - name: KONG_VITALS
                  value: "off"
                - name: KONG_CLUSTER_MTLS
                  value: "pki"
                - name: KONG_CLUSTER_CONTROL_PLANE
                  value: "CLUSTER_CONTROL_PLANE_PLACEHOLDER"
                - name: KONG_CLUSTER_SERVER_NAME
                  value: "CLUSTER_SERVER_NAME_PLACEHOLDER"
                - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
                  value: "CLUSTER_TELEMETRY_ENDPOINT_PLACEHOLDER"
                - name: KONG_CLUSTER_TELEMETRY_SERVER_NAME
                  value: "CLUSTER_TELEMETRY_SERVER_NAME_PLACEHOLDER"
                - name: KONG_CLUSTER_CERT
                  value: "/etc/secrets/kong-cluster-cert/tls.crt"
                - name: KONG_CLUSTER_CERT_KEY
                  value: "/etc/secrets/kong-cluster-cert/tls.key"
                - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
                  value: "system"
                - name: KONG_KONNECT_MODE
                  value: "on"
                - name: KONG_TLS_CERTIFICATE_VERIFY
                  value: "off"
              resources:
                requests:
                  cpu: DATAPLANE_CPU_REQUEST_PLACEHOLDER
                  memory: DATAPLANE_MEMORY_REQUEST_PLACEHOLDER
                limits:
                  cpu: DATAPLANE_CPU_LIMIT_PLACEHOLDER
                  memory: DATAPLANE_MEMORY_LIMIT_PLACEHOLDER
              volumeMounts:
                - name: kong-cluster-cert
                  mountPath: /etc/secrets/kong-cluster-cert
                  readOnly: true
          volumes:
            - name: kong-cluster-cert
              secret:
                secretName: CERT_SECRET_NAME_PLACEHOLDER
